---
title: "ESM 244 - Assignment 2, Task 1"
author: "Claire Madden"
date: "2/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```


### Why Open Science?

Open science, and the larger open access movement, represents an important step in reducing barriers associated with access to information. Scientific research published in an open platform can reach a wide global audience, rather than be kept in the confines of academia and those who have the resources to pay for information. There is growing recognition of the benefits of open science among researchers as well, with many acknowledging that today's problems are far too big for anyone to solve alone and that collaboration and sharing are important to the progression of scientific understanding (McKiernan et al, 2016). However, access is still not universal, and there is room to improve the accessibility and openness of research and information.

One barrier to access that is particularly relevant in developing countries is the need for a computer and internet to access most recently published research. In terms of equity and inclusion, open science may present a barrier to already marginalized groups during the peer review process, and increased transparency may disproportionately negatively impact minority groups such as women and people of color. As Bahlai et al (2019) states, "open peer review assumes that everyone accepts criticism in a friendly way and that there is no such thing as bias, which is demonstrably untrue" and can be especially detrimental to groups that are already experiencing other forms of workplace and career bais.

Through my current group project, we have strived to make our project as open as possible by using all publically available data sources in our analysis. Additionally, now that we have created a transferable decision support tool designed to identify land area most suited to multiple benefit groundwater recharge, we plan to share this tool openly and free of charge with Groundwater Sustainability Agencies throughout California’s Central Valley who are interested in accessing the information generated by the tool. Lastly, we are currently in communication with other non-profit organizations working on similar research and hope to develop a way to make this tool a modular and additive component of a larger effort. 

One barrier to our current project’s openness is the software used to generate the decision support tool. Because of the number and size of spatial datasets we needed to use to complete this project, we were unable to successfully complete the tool in an open source application like RStudio. Using ArcGIS Model Builder was not our first choice, and we hope that in the future as the spatial processing capabilities of RStudio continue to improve, there may be an opportunity to create a version of the tool in an open source platform that could be accessed by any interested user. 

###### References:

1.	McKiernan, E.C. et al. (2016). How open science helps researchers succeed. eLife. 2016; 5: e16800. doi: 10.7554/eLife.16800. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4973366/

2.	Bahlai, C. et al (2018). Open Science Isn't Always Open to All Scientists. American Scientist. https://www.americanscientist.org/article/open-science-isnt-always-open-to-all-scientists 









